name: iris_tools
description: iris tools Library.
version: 0.1.21
homepage: https://iris.ir

publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  community_material_icon: ^5.9.55      # https://materialdesignicons.com/  https://www.fluttericon.com/
  jiffy: ^6.2.1
  file: ^7.0.0
  convert: ^3.1.1
  path: ^1.8.3                          # (path manager)
  android_path_provider: ^0.3.0         # (android directory)
  mime: ^1.0.4
  url_launcher: ^6.1.11
  dio: ^5.2.1+1
  http: ^1.1.0
  connectivity_plus: ^4.0.1
  photo_view: ^0.14.0
  file_picker: ^5.3.2
  audioplayers: ^4.1.0
  video_player: ^2.7.0
  gallery_saver: 2.3.2
  image: ^4.0.17                        # (crop, rotate) alter:https://pub.dev/packages/pic
  image_size_getter: ^2.1.2
  g_json: ^4.1.0
  video_compress: ^3.1.2                # no Web    (thumbnail)
  path_provider: ^2.0.15                # no Web
  disk_space: ^0.2.1                    # no Web
  open_file: ^3.3.2                     # no Web
  flutter_image_compress: ^2.0.3        # no Web
  crypto: ^3.0.3
  collection: any


  iris_db:
#    path: ../../../DartProjects/IrisDB
    git: https://github.com/ali-1989/IrisDB.git


dependency_overrides:
  file: ^7.0.0
  http: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2


flutter:



#-----------------------------------------------------------------
#web_socket_channel: ^2.1.0          # W, https://pub.dev/packages/web_socket_channel
